In [1]:
import pickle

# 反序列化
file_name = "not_fanyi_Lang_korea_韩文"
with open("{0}_code_logs.pkl".format(file_name), "rb") as file:
    code_token_logs = pickle.load(file)

In [2]:
code_token_logs

[(4, 'zh-CN', '[5fffb9]', '<code_id=0>'),
 (4, 'zh-CN', '[-]', '<code_id=1>'),
 (5, 'zh-CN', '[5fffb9]', '<code_id=0>'),
 (5, 'zh-CN', '[-]', '<code_id=1>'),
 (7, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (7, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (7, 'zh-CN', '[-]', '<code_id=2>'),
 (8, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (8, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (8, 'zh-CN', '[-]', '<code_id=2>'),
 (9, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (9, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (9, 'zh-CN', '[-]', '<code_id=2>'),
 (10, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (10, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (10, 'zh-CN', '[-]', '<code_id=2>'),
 (11, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (11, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (11, 'zh-CN', '[-]', '<code_id=2>'),
 (12, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (12, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (12, 'zh-CN', '[-]', '<code_id=2>'),
 (13, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (13, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (13, 'zh-CN', '[-]', '<code_id=2>'),
 (14, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (14, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (14, 'zh-CN', '[-]', '<code_id=2>'),
 (24, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (24, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (24, 'zh-CN', '[-]', '<code_id=2>'),
 (25, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (25, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (25, 'zh-CN', '[-]', '<code_id=2>'),
 (26, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (26, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (26, 'zh-CN', '[-]', '<code_id=2>'),
 (27, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (27, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (27, 'zh-CN', '[-]', '<code_id=2>'),
 (28, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (28, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (28, 'zh-CN', '[-]', '<code_id=2>'),
 (29, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (29, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (29, 'zh-CN', '[-]', '<code_id=2>'),
 (30, 'zh-CN', '[5fffb9]', '<code_id=0>'),
 (30, 'zh-CN', '[-]', '<code_id=1>'),
 (31, 'zh-CN', '[5fffb9]', '<code_id=0>'),
 (31, 'zh-CN', '[-]', '<code_id=1>'),
 (40, 'zh-CN', '[5FFFB9]', '<code_id=0>'),
 (40, 'zh-CN', '[-]', '<code_id=1>'),
 (41, 'zh-CN', '[5FFFB9]', '<code_id=0>'),
 (41, 'zh-CN', '[-]', '<code_id=1>'),
 (44, 'zh-CN', '[5FFFB9]', '<code_id=0>'),
 (44, 'zh-CN', '[-]', '<code_id=1>'),
 (45, 'zh-CN', '[5FFFB9]', '<code_id=0>'),
 (45, 'zh-CN', '[-]', '<code_id=1>'),
 (47, 'zh-CN', '[5FFFB9]', '<code_id=0>'),
 (47, 'zh-CN', '[-]', '<code_id=1>'),
 (48, 'zh-CN', '[ffffff]', '<code_id=0>'),
 (48, 'zh-CN', '[33ff4b]', '<code_id=1>'),
 (48, 'zh-CN', '[-]', '<code_id=2>'),
 (73, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (73, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (73, 'zh-CN', '[-]', '<code_id=2>'),
 (74, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (74, 'zh-CN', '[-]', '<code_id=1>'),
 (77, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (77, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (77, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (77, 'zh-CN', '[-]', '<code_id=3>'),
 (78, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (78, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (78, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (78, 'zh-CN', '[-]', '<code_id=3>'),
 (79, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (79, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (79, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (79, 'zh-CN', '[-]', '<code_id=3>'),
 (80, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (80, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (80, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (80, 'zh-CN', '[-]', '<code_id=3>'),
 (81, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (81, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (81, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (81, 'zh-CN', '[-]', '<code_id=3>'),
 (82, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (82, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (82, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (82, 'zh-CN', '[-]', '<code_id=3>'),
 (83, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (83, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (83, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (83, 'zh-CN', '[-]', '<code_id=3>'),
 (84, 'zh-CN', '[FFEAC6]', '<code_id=0>'),
 (84, 'zh-CN', '[-]', '<code_id=1>'),
 (85, 'zh-CN', '[FFEAC6]', '<code_id=0>'),
 (85, 'zh-CN', '[-]', '<code_id=1>'),
 (86, 'zh-CN', '[FFEAC6]', '<code_id=0>'),
 (86, 'zh-CN', '[-]', '<code_id=1>'),
 (87, 'zh-CN', '[FFEAC6]', '<code_id=0>'),
 (87, 'zh-CN', '[-]', '<code_id=1>'),
 (88, 'zh-CN', '[FFEAC6]', '<code_id=0>'),
 (88, 'zh-CN', '[-]', '<code_id=1>'),
 (89, 'zh-CN', '[FFEAC6]', '<code_id=0>'),
 (89, 'zh-CN', '[-]', '<code_id=1>'),
 (90, 'zh-CN', '[FFEAC6]', '<code_id=0>'),
 (90, 'zh-CN', '[-]', '<code_id=1>'),
 (91, 'zh-CN', '[FFEAC6]', '<code_id=0>'),
 (91, 'zh-CN', '[-]', '<code_id=1>'),
 (92, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (92, 'zh-CN', '[ff5d6b]', '<code_id=1>'),
 (92, 'zh-CN', '[-]', '<code_id=2>'),
 (93, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (93, 'zh-CN', '[ff5d6b]', '<code_id=1>'),
 (93, 'zh-CN', '[-]', '<code_id=2>'),
 (94, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (94, 'zh-CN', '[ff5d6b]', '<code_id=1>'),
 (94, 'zh-CN', '[-]', '<code_id=2>'),
 (95, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (95, 'zh-CN', '[ff5d6b]', '<code_id=1>'),
 (95, 'zh-CN', '[-]', '<code_id=2>'),
 (96, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (96, 'zh-CN', '[ff5d6b]', '<code_id=1>'),
 (96, 'zh-CN', '[-]', '<code_id=2>'),
 (97, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (97, 'zh-CN', '[ff5d6b]', '<code_id=1>'),
 (97, 'zh-CN', '[-]', '<code_id=2>'),
 (98, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (98, 'zh-CN', '[ff5d6b]', '<code_id=1>'),
 (98, 'zh-CN', '[-]', '<code_id=2>'),
 (99, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (99, 'zh-CN', '[ff5d6b]', '<code_id=1>'),
 (99, 'zh-CN', '[-]', '<code_id=2>'),
 (100, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (100, 'zh-CN', '[ff5d6b]', '<code_id=1>'),
 (100, 'zh-CN', '[-]', '<code_id=2>'),
 (101, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (101, 'zh-CN', '[ff5d6b]', '<code_id=1>'),
 (101, 'zh-CN', '[-]', '<code_id=2>'),
 (102, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (102, 'zh-CN', '[-]', '<code_id=1>'),
 (103, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (103, 'zh-CN', '[-]', '<code_id=1>'),
 (104, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (104, 'zh-CN', '[-]', '<code_id=1>'),
 (105, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (105, 'zh-CN', '[-]', '<code_id=1>'),
 (106, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (106, 'zh-CN', '[-]', '<code_id=1>'),
 (107, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (107, 'zh-CN', '[-]', '<code_id=1>'),
 (108, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (108, 'zh-CN', '[-]', '<code_id=1>'),
 (109, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (109, 'zh-CN', '[-]', '<code_id=1>'),
 (110, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (110, 'zh-CN', '[-]', '<code_id=1>'),
 (111, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (111, 'zh-CN', '[-]', '<code_id=1>'),
 (112, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (112, 'zh-CN', '[-]', '<code_id=1>'),
 (114, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (114, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (114, 'zh-CN', '[-]', '<code_id=2>'),
 (116, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (116, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (116, 'zh-CN', '[-]', '<code_id=2>'),
 (118, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (118, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (118, 'zh-CN', '[-]', '<code_id=2>'),
 (120, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (120, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (120, 'zh-CN', '[-]', '<code_id=2>'),
 (122, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (122, 'zh-CN', '[-]', '<code_id=1>'),
 (123, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (123, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (123, 'zh-CN', '[-]', '<code_id=2>'),
 (124, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (124, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (124, 'zh-CN', '[-]', '<code_id=2>'),
 (126, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (126, 'zh-CN', '[ecd77b]', '<code_id=1>'),
 (126, 'zh-CN', '[-]', '<code_id=2>'),
 (127, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (127, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (127, 'zh-CN', '[bf00ff]', '<code_id=2>'),
 (127, 'zh-CN', '[-]', '<code_id=3>'),
 (128, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (128, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (128, 'zh-CN', '[-]', '<code_id=2>'),
 (129, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (129, 'zh-CN', '[5fffb9]', '<code_id=1>'),
 (129, 'zh-CN', '[-]', '<code_id=2>'),
 (130, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (130, 'zh-CN', '[FF0000]', '<code_id=1>'),
 (130, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (130, 'zh-CN', '[FFA500]', '<code_id=3>'),
 (130, 'zh-CN', '[-]', '<code_id=4>'),
 (131, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (131, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (131, 'zh-CN', '[-]', '<code_id=2>'),
 (132, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (132, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (132, 'zh-CN', '[-]', '<code_id=2>'),
 (134, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (134, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (134, 'zh-CN', '[-]', '<code_id=2>'),
 (136, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (136, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (136, 'zh-CN', '[-]', '<code_id=2>'),
 (138, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (138, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (138, 'zh-CN', '[-]', '<code_id=2>'),
 (140, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (140, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (140, 'zh-CN', '[-]', '<code_id=2>'),
 (142, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (142, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (142, 'zh-CN', '[-]', '<code_id=2>'),
 (144, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (144, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (144, 'zh-CN', '[-]', '<code_id=2>'),
 (146, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (146, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (146, 'zh-CN', '[-]', '<code_id=2>'),
 (148, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (148, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (148, 'zh-CN', '[-]', '<code_id=2>'),
 (150, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (150, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (150, 'zh-CN', '[-]', '<code_id=2>'),
 (152, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (152, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (152, 'zh-CN', '[-]', '<code_id=2>'),
 (154, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (154, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (154, 'zh-CN', '[-]', '<code_id=2>'),
 (156, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (156, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (156, 'zh-CN', '[-]', '<code_id=2>'),
 (158, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (158, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (158, 'zh-CN', '[-]', '<code_id=2>'),
 (160, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (160, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (160, 'zh-CN', '[-]', '<code_id=2>'),
 (162, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (162, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (162, 'zh-CN', '[-]', '<code_id=2>'),
 (164, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (164, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (164, 'zh-CN', '[-]', '<code_id=2>'),
 (166, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (166, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (166, 'zh-CN', '[-]', '<code_id=2>'),
 (168, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (168, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (168, 'zh-CN', '[-]', '<code_id=2>'),
 (170, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (170, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (170, 'zh-CN', '[-]', '<code_id=2>'),
 (172, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (172, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (172, 'zh-CN', '[-]', '<code_id=2>'),
 (174, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (174, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (174, 'zh-CN', '[-]', '<code_id=2>'),
 (176, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (176, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (176, 'zh-CN', '[-]', '<code_id=2>'),
 (178, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (178, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (178, 'zh-CN', '[-]', '<code_id=2>'),
 (180, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (180, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (180, 'zh-CN', '[-]', '<code_id=2>'),
 (182, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (182, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (182, 'zh-CN', '[-]', '<code_id=2>'),
 (184, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (184, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (184, 'zh-CN', '[-]', '<code_id=2>'),
 (186, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (186, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (186, 'zh-CN', '[-]', '<code_id=2>'),
 (188, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (188, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (188, 'zh-CN', '[-]', '<code_id=2>'),
 (190, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (190, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (190, 'zh-CN', '[-]', '<code_id=2>'),
 (192, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (192, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (192, 'zh-CN', '[-]', '<code_id=2>'),
 (194, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (194, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (194, 'zh-CN', '[-]', '<code_id=2>'),
 (196, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (196, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (196, 'zh-CN', '[-]', '<code_id=2>'),
 (198, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (198, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (198, 'zh-CN', '[-]', '<code_id=2>'),
 (200, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (200, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (200, 'zh-CN', '[-]', '<code_id=2>'),
 (202, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (202, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (202, 'zh-CN', '[-]', '<code_id=2>'),
 (204, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (204, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (204, 'zh-CN', '[-]', '<code_id=2>'),
 (206, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (206, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (206, 'zh-CN', '[-]', '<code_id=2>'),
 (208, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (208, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (208, 'zh-CN', '[-]', '<code_id=2>'),
 (210, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (210, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (210, 'zh-CN', '[-]', '<code_id=2>'),
 (212, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (212, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (212, 'zh-CN', '[-]', '<code_id=2>'),
 (213, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (213, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (213, 'zh-CN', '[-]', '<code_id=2>'),
 (215, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (215, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (215, 'zh-CN', '[-]', '<code_id=2>'),
 (217, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (217, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (217, 'zh-CN', '[-]', '<code_id=2>'),
 (219, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (219, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (219, 'zh-CN', '[-]', '<code_id=2>'),
 (221, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (221, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (221, 'zh-CN', '[-]', '<code_id=2>'),
 (223, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (223, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (223, 'zh-CN', '[-]', '<code_id=2>'),
 (225, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (225, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (225, 'zh-CN', '[-]', '<code_id=2>'),
 (227, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (227, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (227, 'zh-CN', '[-]', '<code_id=2>'),
 (229, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (229, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (229, 'zh-CN', '[-]', '<code_id=2>'),
 (231, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (231, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (231, 'zh-CN', '[-]', '<code_id=2>'),
 (233, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (233, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (233, 'zh-CN', '[-]', '<code_id=2>'),
 (235, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (235, 'zh-CN', '[5FFFB9]', '<code_id=1>'),
 (235, 'zh-CN', '[-]', '<code_id=2>'),
 (237, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (237, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (237, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (237, 'zh-CN', '[-]', '<code_id=3>'),
 (238, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (238, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (238, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (238, 'zh-CN', '[-]', '<code_id=3>'),
 (239, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (239, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (239, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (239, 'zh-CN', '[-]', '<code_id=3>'),
 (240, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (240, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (240, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (240, 'zh-CN', '[-]', '<code_id=3>'),
 (241, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (241, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (241, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (241, 'zh-CN', '[-]', '<code_id=3>'),
 (242, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (242, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (242, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (242, 'zh-CN', '[-]', '<code_id=3>'),
 (243, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (243, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (243, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (243, 'zh-CN', '[-]', '<code_id=3>'),
 (245, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (245, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (245, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (245, 'zh-CN', '[-]', '<code_id=3>'),
 (247, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (247, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (247, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (247, 'zh-CN', '[-]', '<code_id=3>'),
 (248, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (248, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (248, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (248, 'zh-CN', '[-]', '<code_id=3>'),
 (249, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (249, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (249, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (249, 'zh-CN', '[-]', '<code_id=3>'),
 (250, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (250, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (250, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (250, 'zh-CN', '[-]', '<code_id=3>'),
 (251, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (251, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (251, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (251, 'zh-CN', '[-]', '<code_id=3>'),
 (253, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (253, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (253, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (253, 'zh-CN', '[-]', '<code_id=3>'),
 (255, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (255, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (255, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (255, 'zh-CN', '[-]', '<code_id=3>'),
 (259, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (259, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (259, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (259, 'zh-CN', '[-]', '<code_id=3>'),
 (260, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (260, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (260, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (260, 'zh-CN', '[-]', '<code_id=3>'),
 (261, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (261, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (261, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (261, 'zh-CN', '[-]', '<code_id=3>'),
 (262, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (262, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (262, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (262, 'zh-CN', '[-]', '<code_id=3>'),
 (264, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (264, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (264, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (264, 'zh-CN', '[-]', '<code_id=3>'),
 (265, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (265, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (265, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (265, 'zh-CN', '[-]', '<code_id=3>'),
 (266, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (266, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (266, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (266, 'zh-CN', '[-]', '<code_id=3>'),
 (267, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (267, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (267, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (267, 'zh-CN', '[-]', '<code_id=3>'),
 (268, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (268, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (268, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (268, 'zh-CN', '[-]', '<code_id=3>'),
 (269, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (269, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (269, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (269, 'zh-CN', '[-]', '<code_id=3>'),
 (270, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (270, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (270, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (270, 'zh-CN', '[-]', '<code_id=3>'),
 (271, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (271, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (271, 'zh-CN', '[5FFFB9]', '<code_id=2>'),
 (271, 'zh-CN', '[-]', '<code_id=3>'),
 (272, 'zh-CN', '[FBFFFF]', '<code_id=0>'),
 (272, 'zh-CN', '[FAB76A]', '<code_id=1>'),
 (272, 'zh-CN', '[5FFFB9]', '<code_id=2>'),

In [3]:
import pandas as pd

df = pd.read_excel("translation_result_of_fine-tuned-models_nllb-200-1.3B_zh2ko_1107.xlsx")
df

,source,candidates
0,07时59分,</s>kor_Hang 07时59分</s>
1,<start>魔音<middle>마음<end>乱心,</s>kor_Hang<start> 마음<end> 이 안심</s>
2,“零”，“一”，“二”，“三”，“四”，“五”，“六”，“七”，“八”，“九”，“十”，“十...,"</s>kor_Hang 떡이 작은 떡, 떡이 하나, 떡이 두, 떡이 세, 떡이 네,..."
3,<start>服饰<middle>장신구<end>·狰骨怒涛,</s>kor_Hang<start> 장신구<end> -]골노정</s>
4,<start>操作<middle>조작<end>太频繁，请<code_id=0>1<code...,</s>kor_Hang<start> 조작<end> 빈도가 너무 높습니다. <code...
...,...,...
791,2888#r元#r礼#r包,</s>kor_Hang 2888#r원 #r#礼#r包</s>
792,"请勿相信任何声称<start>自己<middle>자신<end>认识官方人员,然后要求线下转...",</s>kor_Hang<start> 자신<end> 만의 <start> 알 수 있는 ...
793,<start>区服<middle>서버<end>列表载<start>失败<middle>실패...,</s>kor_Hang<start> 서버<end> 로드 <start> 실패<end>...
794,<start>个人<middle>개인<end><start>竞技场<middle>아레나<...,</s>kor_Hang<start> 개인<end> <start> 아레나<end></s>
795,<start>神域<middle>신역<end><start>boss<middle>보스<...,</s>kor_Hang<start> 신역<end> <start> 보스<end></s>

In [4]:
for log in code_token_logs:
    index, column, code, token = log
    df.loc[index, "candidates"] = str(df.loc[index, "candidates"]).replace(token, code)

In [5]:
df

,source,candidates
0,07时59分,</s>kor_Hang 07时59分</s>
1,<start>魔音<middle>마음<end>乱心,</s>kor_Hang<start> 마음<end> 이 안심</s>
2,“零”，“一”，“二”，“三”，“四”，“五”，“六”，“七”，“八”，“九”，“十”，“十...,"</s>kor_Hang 떡이 작은 떡, 떡이 하나, 떡이 두, 떡이 세, 떡이 네,..."
3,<start>服饰<middle>장신구<end>·狰骨怒涛,</s>kor_Hang<start> 장신구<end> -]골노정</s>
4,<start>操作<middle>조작<end>太频繁，请<code_id=0>1<code...,</s>kor_Hang<start> 조작<end> 빈도가 너무 높습니다. [5fff...
...,...,...
791,2888#r元#r礼#r包,</s>kor_Hang 2888#r원 #r#礼#r包</s>
792,"请勿相信任何声称<start>自己<middle>자신<end>认识官方人员,然后要求线下转...",</s>kor_Hang<start> 자신<end> 만의 <start> 알 수 있는 ...
793,<start>区服<middle>서버<end>列表载<start>失败<middle>실패...,</s>kor_Hang<start> 서버<end> 로드 <start> 실패<end>...
794,<start>个人<middle>개인<end><start>竞技场<middle>아레나<...,</s>kor_Hang<start> 개인<end> <start> 아레나<end></s>
795,<start>神域<middle>신역<end><start>boss<middle>보스<...,</s>kor_Hang<start> 신역<end> <start> 보스<end></s>

In [6]:
df.to_excel("not_fanyi_Lang_korea_韩文_translated.xlsx")