In [1]:
import numpy as np
import pandas as pd

df = pd.read_excel("實時同步翻譯文本.xlsx")
df.replace(np.nan, None, inplace=True)  # replace np.nan with None
df

            简体1           简体2   简体3
0          狩猎商人          None  None
1            图鉴          None  None
2    再次点击使用加速药水          None  None
3     点击任务的传送按钮          None  None
4        点击确认传送          None  None
..          ...           ...   ...
576   第6日完成所有任务          None  None
577   第7日完成所有任务          None  None
578    狩猎商人声望奖励  狩猎商人Lv.1每日供给  None
579    狩猎商人声望奖励  狩猎商人Lv.2每日供给  None
580    狩猎商人声望奖励  狩猎商人Lv.3每日供给  None

[581 rows x 3 columns]

In [2]:
import re

import pandas as pd

# 读取Excel文件
df_glossary = pd.read_excel("glossary_all.xlsx")

# 只保留需要的两列
df_glossary = df_glossary[["zh-CN", "ko"]]

# 删除任何包含NaN的行
df_glossary = df_glossary.dropna(how='any')

# 按照中文列去重
df_glossary = df_glossary.drop_duplicates(subset="zh-CN", keep=False)

# 确保'zh-CN'和'ko'列中的所有元素都是字符串
df_glossary['zh-CN'] = df_glossary['zh-CN'].astype(str)
df_glossary['ko'] = df_glossary['ko'].astype(str)

# 删除包含数字的行
mask = df_glossary.applymap(lambda x: bool(re.search(r'\d', x)))
df_glossary = df_glossary[~mask.any(axis=1)]

#按照长度降序排布
df_glossary["zh-CN_length"] = df_glossary["zh-CN"].str.len()
df_glossary = df_glossary.sort_values("zh-CN_length", ascending=False)
df_glossary = df_glossary.drop('zh-CN_length', axis=1)
df_glossary

C:\Users\Longtukorea\AppData\Local\Temp\ipykernel_73664\3809072538.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  mask = df_glossary.applymap(lambda x: bool(re.search(r'\d', x)))

                 zh-CN                  ko
52988  减弱受击时最终受到伤害的百分比       받는 최종피해 비율 감소
10069  遗迹冒险boss重生券(自选)    유적 모험 보스 부활권(선택)
38866  精灵提升，守护圣灵副本购买次数       성령수호 던전 구매 횟수
13181  AA~SS骑士碎片宝箱（随机）  AA~SS 기사 조각 상자(랜덤)
52994  攻击时增加技能造成伤害的百分比       공격 시 스킬 피해 증가
...                ...                 ...
4354                 魔                  악마
45769                隐                  은신
45745                云                  구름
33258                庆                  축제
45473                吻                  키스

[35393 rows x 2 columns]

In [3]:
df_glossary.set_index("zh-CN", inplace=True)
glossary_dict = df_glossary["ko"].to_dict()
glossary_dict

{'减弱受击时最终受到伤害的百分比': '받는 최종피해 비율 감소',
 '遗迹冒险boss重生券(自选)': '유적 모험 보스 부활권(선택)',
 '精灵提升，守护圣灵副本购买次数': '성령수호 던전 구매 횟수',
 'AA~SS骑士碎片宝箱（随机）': 'AA~SS 기사 조각 상자(랜덤)',
 '攻击时增加技能造成伤害的百分比': '공격 시 스킬 피해 증가',
 '雷奥妮·阿德勒（蕾奥妮·罗兰）': '레오니 아들러(레오니 롤랜드)',
 'AA~SS骑士圣器宝箱（随机）': 'AA~SS 기사 성구 상자(랜덤)',
 '神王大人，您目前还没有邮件哦！': '현재 우편이 없습니다!',
 '真·探险BOSS宝箱(深渊)': '진·탐험 보스 상자(심연)',
 '传送门就在眼前啦，溜了溜了~': '전송문이 눈앞에 있어요~',
 '真·探险BOSS宝箱(普通)': '진·탐험 보스 상자(일반)',
 '真·探险BOSS宝箱(噩梦)': '진·탐험 보스 상자(악몽)',
 '红色精灵卡片(自选)(废弃）': '신화 정령 카드(선택)(폐기)',
 '真·探险BOSS宝箱(困难)': '진·탐험 보스 상자(어려움)',
 'A~SS骑士圣器宝箱（随机）': 'A~SS 기사 성구 보물상자(랜덤)',
 '真·探险BOSS宝箱(简单)': '진·탐험 보스 상자(쉬움)',
 '橙色精灵卡片(自选)(废弃）': '전설 정령 카드(선택)(폐기)',
 '粉色精灵卡片(自选)(废弃）': '에픽 정령 카드(선택)(폐기)',
 '真·探险BOSS宝箱(中等)': '진·탐험 보스 상자(중급)',
 'A~SS骑士碎片宝箱（随机）': 'A~SS 기사 조각 상자(랜덤)',
 'B~SS骑士碎片宝箱（随机）': 'B~SS 기사 조각 상자(랜덤)',
 '奔驰汽车原产于哪一个国家？': '벤츠의 생산 국가는?',
 'BOSS-坐骑boss狐狸': 'BOSS-탈것boss영호',
 '中级BOSS体力果(自选)': '중급 보스 체력 열매(선택)',
 '懒人福利，自动进行战盟任务': '연맹 퀘스트 자동 진행',
 '小的们！抓紧时间收集宝贝！': '서둘러 보물을 수집해!',
 '大量金币，深海宝库购买次数': '심해 보물창고 구매 횟수',
 '神仆提升，神仆副本扫荡次数': '신복 던전 소탕 횟수',
 '高级BOSS体力果(自选)': '상급 보스 체력 열매(선택)',
 'BOSS-坐骑boss麒麟': 'BOSS-탈것boss기린',
 '精灵提升，守护圣灵购买次数': '성령수호 구매 횟수',
 'BOSS-坐骑boss凤凰': 'BOSS-탈것boss봉황',
 'BOSS-坐骑boss飞龙': 'BOSS-탈것boss비룡',
 'BOSS-坐骑boss魔虎': 'BOSS-탈것boss마호',
 '核糖核酸的英文缩写是什么？': '리보핵산의 영어 약자는?',
 '极致升级，星空秘境购买次数': '하늘비경 구매 횟수',
 '愚人节是在每一年的哪一天？': '만우절은 언제인가?',
 '刺客怒气技-范围(玩家)': '자객궁극기-범위(유저)',
 '粉色传感装置礼包(随机)': '에픽 감지 장치 패키지(랜덤)',
 '高级坐骑属性礼包(随机)': '상급 탈것 속성 패키지(랜덤)',
 '高级坐骑幻化礼包(自选)': '상급 탈것 장착 패키지(선택)',
 '冒险boss礼包(自选)': '모험 보스 패키지(선택)',
 '悄悄地~~~悄悄地~~~': '몰래~몰래~',
 '高级进阶随机礼包(自选)': '상급 진화 랜덤 패키지(선택)',
 '至尊坐骑属性礼包(随机)': '지존 탈것 속성 패키지(랜덤)',
 '深海守护者  鱿鱼 碎片': '심해 수호자 조각',
 '沁染流年·永恒蓝（染料）': '심염유년·영구 남색(염료)',
 '粉色传感装置礼包(自选)': '에픽 감지 장치 패키지(선택)',
 '竞技争锋，竞技场购买次数': '결투장 구매 횟수',
 '我国最大的淡水湖是什么？': '중국 최대 담수호는?',
 '刺客怒气技-伤害(玩家)': '자객궁극기-피해(유저)',
 '至尊坐骑幻化礼包(自选)': '지존 탈것 장착 패키지(선택)',
 '圣炎天使优惠宝箱(自选)': '불꽃천사 혜택 상자(선택)',
 '中级坐骑属性礼包(随机)': '중급 탈것 속성 패키지(랜덤)',
 '我国最大的咸水湖是什么？': '중국 최대 함수호는?',
 '圣枪无极优惠宝箱(自选)': '성총 무극 혜택 상자(선택)',
 '红色传感装置礼包(随机)': '신화 감지 장치 패키지(랜덤)',
 '祝你春节快乐，牛年大吉。': '즐거운 설날 보내세요.',
 '沃尔夫冈·里希特霍芬男爵': '볼프강 리히토펜(남작)',
 '初级坐骑属性礼包(随机)': '하급 탈것 속성 패키지(랜덤)',
 '有了这种力量，一定可以！': '이 힘만 있으면 반드시!',
 '代表着和平的植物是什么？': '평화를 상징하는 식물은?',
 '代表着和平的动物是什么？': '평화를 상징하는 동물은?',
 '探险BOSS宝箱(中等)': '탐험 보스 상자(중급)',
 '探险BOSS宝箱(噩梦)': '탐험 보스 상자(악몽)',
 '猩红女帝优惠宝箱(自选)': '핏빛 여제 혜택 상자(선택)',
 '探险BOSS宝箱(深渊)': '탐험 보스 상자(심연)',
 '探险BOSS宝箱(普通)': '탐험 보스 상자(일반)',
 '探险BOSS宝箱(困难)': '탐험 보스 상자(어려움)',
 '御剑怒气技-范围(玩家)': '어검 궁극기-범위(유저)',
 '御剑怒气技-伤害(玩家)': '어검 궁극기-피해(유저)',
 '金玉满堂优惠宝箱(自选)': '금옥만당 혜택 상자(선택)',
 '龙之女皇优惠宝箱(自选)': '용족 여황제 혜택 상자(선택)',
 '探险BOSS宝箱(简单)': '탐험 보스 상자(쉬움)',
 'BOSS-坐骑boss狼': 'BOSS-탈것boss늑대',
 '《全职高手》中的主角是？': '《전직고수》의 주인공은?',
 '现在就已经收获颇丰了啊~': '이미 충분히 수확했어~',
 '神殿圣女(随机BOSS)': '신전성녀(랜덤BOSS)',
 '仙台境开放问天路—仙王': '선대경 문천로-선왕 오픈',
 '战无敌优惠宝箱(自选)': '전사 무적 혜택 상자(선택)',
 '当前BOSS挑战次数：': '현재 BOSS도전 횟수:',
 '世界最高的塔是哪一座？': '세계에서가장 높은 탑은?',
 '当前剩余大型魔星矿数量': '현재 남은 대형광석 수량',
 '仙台境开放问天路-仙台': '선대경 진천로-선대 오픈',
 '太初石(男)/太初石男': '태초석(남)',
 '哪种动物是北极的象征？': '북극을 상징하는 동물은?',
 '势力炼气-神纹boss': '길드 기 단련-문양boss',
 '历尽苦难，成功获取传承': '우여곡절 끝에 전승 성공',
 '太初石(女)/太初石女': '태초석(여)',
 '仙帝境开放问天路—仙帝': '선제경 문천로-선제 오픈',
 '魔像崖退出场景buff': '골렘절벽 맵 퇴장buff',
 '福利礼包（测试功能用）': '보상선물(테스트 기능용)',
 '基  础  防  御：': '기 본 방 어:',
 '下列玩家处于死亡状态：': '사망 상태인 유저:',
 '木灵誓约·装备（随机）': '목령 서약·장비(랜덤)',
 '黄钻兑换券(地宫探险)': '황금 다이아 교환권(지하탐험)',
 '哈哈，看我的对话气泡。': '하하, 내 말풍선을 봐.',
 '【小鸡大作战】鹰-机关': '【병아리 대작전】매-기관',
 'yyyy年MM月dd日': 'yyyy년 MM월 dd일',
 '木灵誓约·精灵（随机）': '목령 서약·정령(랜덤)',
 '提示 : 本次研究需要': '알림: 이번 연구 필요',
 '界主境开放问天路—神王': '계주경 문천로-신왕 오픈',
 '下列玩家处于飞行状态：': '비행 상태인 유저:',
 '号称我国第一神山的是？': '중국 제일 신의 산은?',
 '火枪属性丹礼包(随机)': '라이플 속성 단약 패키지(랜덤)',
 '元  素  防  御：': '원 소 방 어:',
 '元  素  攻  击：': '원 소 공 격:',
 '《我的大学》的作者是？': '《나의 대학》의 저자는?',
 '你的队伍正在重新匹配!': '다시 매칭 중입니다!',
 '混沌魔主是不会失败的！': '혼돈마주는 지지 않아!',
 '基  础  命  中：': '기 본 명 중:',
 '你已经在自己的服务器了': '자신의 서버입니다.',
 '主宰大人是不会失败的！': '제왕님은 지지 않아!',
 '当  前  攻  击：': '현 재 공 격:',
 '原生魔血精/元生魔血精': '원생 마혈요괴',
 '元神加速单|元神加速丹': '원신 가속단',
 '粉钻兑换券(地宫探险)': '핑크 다이아 교환권(지하탐험)',
 '莱恩酒馆相遇卡(自选)': '레인 술집 데이트권(선택)',
 '对目标攻击造成的伤害值': '목표에게 입히는 피해값',
 '增加攻击造成伤害的强度': '공격 피해 증가 강도',
 '圣灵属性丹礼包(随机)': '성령 속성 단약 패키지(랜덤)',
 '比上次挑战获得经验提升': '획득 경험치 증가',
 'SS级骑士圣器(自选)': 'SS급 기사 성구(선택)',
 '当  前  命  中：': '현 재 명 중:',
 '魔灵属性丹礼包(随机)': '마령 속성 단약 패키지(랜덤)',
 '当  前  防  御：': '현 재 방 어:',
 '【特级】攻击增益自选箱': '[최고급] 공격버프 선택상자',
 'AA级骑士圣器(自选)': 'AA급 기사 성구(선택)',
 '宠物属性丹礼包(随机)': '펫 속성 단약 패키지(랜덤)',
 '势力BOSS正在挑战中': '길드BOSS 도전 중',
 '当  前  生  命：': '현 재 H P:',
 '首饰真龙石礼包(自选)': '장신구 진룡석 패키지(선택)',
 '当  前  闪  避：': '현 재 회 피:',
 'BOSS体力果(自选)': '보스 체력 열매(선택)',
 '快跑！快跑！被发现了！': '도망쳐! 들켰어!',
 '羽翼属性丹礼包(随机)': '날개 속성 단약 패키지(랜덤)',
 '首饰真龙石礼包(随机)': '장신구 진룡석 패키지(랜덤)',
 '神秘酒坊相遇卡(自选)': '신비한 양조장 데이트권(선택)',
 '核心……已……毁坏……': '핵심이…파괴됐어…',
 '基  础  闪  避：': '기 본 회 피:',
 '《桃花源记》的作者是？': '《도화원기》의 저자는?',
 '修罗王罗侯(boss)': '수라왕 나후(보스)',
 '飞升管理人/飞升管理员': '비승 관리인',
 '基  础  生  命：': '기 본 H P:',
 '《醉翁亭记》的作者是？': '《취옹정기》의 저자는?',
 '神域龙怒宝沁钯随机神兵': '신역 용의 분노 보심파 랜덤 신병',
 '基  础  攻  击：': '기 본 공 격:',
 '圣盾属性丹礼包(随机)': '신성 방패 속성 단약 패키지(랜덤)',
 '《聊斋志异》的作者是？': '《요재지이》의 저자는?',
 '艾尔瑞奥尼·莉莉安苔丝': '에를리오네 릴리안테스',
 '《四世同堂》的作者是？': '《사세동당》의 저자는?',
 '《再别康桥》的作者是？': '《재별강교》의 저자는?',
 '欧阳晓生boss技能': '구양효생 BOSS스킬',
 '攻击BOSS伤害增加': 'BOSS공격 피해 증가',
 '《儿童与家庭童话集》': '《어린이와 가정 동화집》',
 '【获得条件】金镶玉：': '【획득 조건】금양옥：',
 '建造灵塔#r抵御进攻': '영탑 건설#r공격 방어',
 '快来进入挑战一次吧！': '어서 도전해 보세요!',
 '攻击光环buff范围': '공격 고리 buff범위',
 '紫色核心礼包(随机)': '영웅 코어 패키지(랜덤)',
 '每日挑战免费BOSS': '매일 BOSS 무료 도전',
 '无极战境·幽月境获取': '무극전장·유월경에서 획득',
 '金色核心礼包(自选)': '초월 코어 패키지(선택)',
 '女仆水晶配方(随机)': '메이드 수정 배합(랜덤)',
 '【塔防副本】攻击伤害': '【탑방어 던전】공격 피해',
 '【塔防副本】攻击范围': '【탑방어 던전】공격 범위',
 '南皇泽儿boss普攻': '남황택아boss일반공격',
 'A级骑士圣器(自选)': 'A급 기사 성구(선택)',
 '马致远是唐代作家么？': '마치원은 당대 작가인가?',
 '陈家家丁/陈家庄家丁': '진씨댁 하인',
 '套装收集超级tips': '세트수집 초특급 힌트',
 '终极传感装置(跳跃)': '최종 감지 장치(도약)',
 '金色核心礼包(随机)': '초월 코어 패키지(랜덤)',
 '终极传感装置(觉醒)': '최종 감지 장치(각성)',
 '欧阳晓生boss普攻': '구양효생boss일반공격',
 '阿贝拉尔多·斯福尔扎': '아베라르도 스포르차',
 '《聊斋志异》的作者是': '《요재지이》의 저자는?',
 '大涅仙法赋予专属分身': '대열선법 부여 전용 분신',
 '当前暂无任何属性加成': '속성 보너스가 없습니다.',
 '《羊脂球》的作者是？': '《비곗덩어리》의 저자는?',
 'A级骑士圣器(随机)': 'A급 기사 성구(랜덤)',
 '你喜欢的食物是什么？': '좋아하는 음식이 뭐예요?',
 '赶快进行一次挑战吧！': '어서 도전해 보세요!',
 '玉面神王（灵狐血脉）': '옥면신왕(영호 혈맥)',
 '将精彩分享给你的好友': '친구에게 공유하기',
 '《物种起源》的作者是': '《종의 기원》의 저자는?',
 'B级骑士圣器(随机)': 'B급 기사 성구(랜덤)',
 '橙色精灵卡片(随机)': '전설 정령 카드(랜덤)',
 '太初符印·阳（衣服）': '태초부인·양(갑옷)',
 '再次挑战免费BOSS': 'BOSS 무료 재도전',
 '魔渊神王（狂战血脉）': '마연신왕(광전사 혈맥)',
 '神话饰品魔卷(自选)': '신화 장식품 마법 스크롤(선택)',
 '橙色核心礼包(随机)': '전설 코어 패키지(랜덤)',
 '至尊骑士圣器(随机)': '지존 기사 성구(랜덤)',
 '橙色核心礼包(自选)': '전설 코어 패키지(선택)',
 '防御光环buff范围': '방어 고리 buff범위',
 '神话基础魔卷(自选)': '신화 기본 마법 스크롤(선택)',
 '战兽助战提供超强加成': '전투신수의 강력한 도움',
 '秘境专属定时BOSS': '비경 전용 기한BOSS',
 '神临殿相遇卡(自选)': '신림전 데이트권(선택)',
 '仙宝丨青庭天禄·#r': '선보丨청정천록·#r',
 '精灵之魂礼盒(自选)': '정령의 혼 선물함(선택)',
 '最早的农作物是什么?': '최초 농작물은?',
 '幻化开启超级tips': '변신 활성화 초특급 힌트',
 '仙宝丨皎宇辟邪·#r': '선보丨교우벽사·#r',
 '仙宝丨焰寂凤凰·#r': '선보丨염적봉황·#r',
 '无极战境·赤阳境获取': '무극전장·적양경에서 획득',
 '俄罗斯的国酒是什么？': '러시아의 대표 술은?',
 '仙宝丨承天元绪·#r': '선보丨승천원서·#r',
 '修罗鬼帅boss技能': '수라귀사 BOSS스킬',
 '武君神王（刺客血脉）': '무군신왕(자객 혈맥)',
 'S级骑士圣器(随机)': 'S급 기사 성구(랜덤)',
 '血海妖僧(boss)': '혈해요승(보스)',
 '获得星魂“星辰小人”': '성혼 “성신소인” 획득',
 '强韧的阿瓦尔战士亡灵': '강인한 아바르 전사 망령',
 '圣器开启超级tips': '성구 활성화 초특급 힌트',
 '暂未激活任何融神属性': '융신 속성 미활성',
 '沃尔夫冈·里希特霍芬': '볼프강 리히토펜',
 '心港屋相遇卡(自选)': '심항옥 데이트권(선택)',
 '试炼长老boss技能': '시련장로 BOSS스킬',
 '黑金核心礼包(随机)': '유물 코어 패키지(랜덤)',
 '黑金核心礼包(自选)': '유물 코어 패키지(선택)',
 '获得星魂“千手佛陀”': '성혼 “천수불타” 획득',
 '获得星魂“绝世剑域”': '성혼 “절세검역” 획득',
 '获得星魂“生命古树”': '성혼 “생명나무” 획득',
 '真武战场BOSS掉落': '진무전장BOSS 드랍',
 '获得星魂“光明之神”': '성혼 “빛의 신” 획득',
 '和我一起守护仙血吧！': '함께 선혈을 수호해요!',
 'B级骑士圣器(自选)': 'B급 기사 성구(선택)',
 '南皇泽儿boss技能': '남황택아 BOSS스킬',
 '虚空幻灵boss技能': '허공환영 BOSS스킬',
 '战姬徽章礼包(随机)': '미호 휘장 패키지(랜덤)',
 '啡林厅相遇卡(自选)': '페린홀 데이트권(선택)',
 '进阶水晶礼包(随机)': '진화 수정 패키지(랜덤)',
 '你已飞至最低飞行高度': '최저 비행 고도입니다.',
 '苍灵秘境世界BOSS': '신령비경 월드BOSS',
 '《龙须沟》的作者是？': '《용수구》의 저자는?',
 '石中剑的持有者是谁？': '석중검의 소유자는?',
 '粉色核心礼包(自选)': '에픽 코어 패키지(선택)',
 '太古主宰排名降低提醒': '태고주재 랭킹 강등 알림',
 '幸运骑士圣器(随机)': '행운의 기사 성구(랜덤)',
 '伟大祖国灵魂的诞生日': '위대한 조국 영혼 탄생일',
 '红色核心礼包(随机)': '신화 코어 패키지(랜덤)',
 '千回百转，还是炼丹好': '뭐니 뭐니 해도 연단이 최고',
 '传说基础魔卷(自选)': '레전드 기본 마법 스크롤(선택)',
 '超值骑士神兵(自选)': '초특급 기사 신병(선택)',
 '星界门相遇卡(自选)': '성계문 데이트권(선택)',
 '我国第一部神话集是？': '중국 첫 번째 신화집은?',
 '我国谁发明了麻沸散？': '마비산을 발견한 사람은?',
 '炫彩核心礼包(随机)': '무지개 코어 패키지(랜덤)',
 '红色精灵卡片(随机)': '신화 정령 카드(랜덤)',
 '神玉只属于灵皇大人！': '신옥은 요황님의 것이다!',
 '高级骑士圣器(自选)': '상급 기사 성구(선택)',
 '时空，是永恒的囚牢！': '시공은 영원한 감옥이다!',
 '高级骑士圣器(随机)': '상급 기사 성구(랜덤)',
 '哈哈，看我的头像框。': '하하, 내 프로필을 봐.',
 '修罗鬼帅boss普攻': '수라귀사boss일반공격',
 '传说饰品魔卷(自选)': '레전드 장식품 마법 스크롤(선택)',
 '红色核心礼包(自选)': '신화 코어 패키지(선택)',
 '库房总管/仓库管理员': '창고 관리인',
 '装备武魂全面提升属性': '무혼 장착 시 속성 증가',
 '这是您自己的榜单排名': '자신의 랭킹 순위입니다.',
 '坐骑狐狸boss技能': '탈것 여우 BOSS스킬',
 '坐骑飞龙boss技能': '탈것 비룡 BOSS스킬',
 '意大利的首都是哪里？': '이탈리아의 수도는?',
 '坐骑开启超级tips': '탈것 활성화 초특급 힌트',
 '坐骑凤凰boss技能': '탈것 봉황 BOSS스킬',
 '坐骑魔虎boss技能': '탈것 마호 BOSS스킬',
 '灵宠开启超级tips': '영혼펫 활성화 초특급 힌트',
 '坐骑麒麟boss技能': '탈것 기린 BOSS스킬',
 '粉色精灵卡片(随机)': '에픽 정령 카드(랜덤)',
 '精灵开启超级tips': '정령 활성화 초특급 힌트',
 '战宠开启超级tips': '전투펫 활성화 초특급 힌트',
 '粉色核心礼包(随机)': '에픽 코어 패키지(랜덤)',
 'S级骑士圣器(自选)': 'S급 기사 성구(선택)',
 '邪龙套装石(狂战士)': '사룡 세트석 (버서커)',
 '圣命堂相遇卡(自选)': '성명당 데이트권(선택)',
 '全部太虚绘卷等级奖励': '전체 태허족자 레벨 보상',
 '天骄战机器人普攻逻辑': '흉노전로봇 일반공격 로직',
 '勇者斗恶龙伤害排行榜': '드래곤 퀘스트 피해랭킹',
 '蜕凡登仙开放超凡等级': '선계경지 초월 레벨 오픈',
 '神兵开启超级tips': '신병 활성화 초특급 힌트',
 '极品骑士圣器(随机)': '최상급 기사 성구(랜덤)',
 '仙帝境开放高级套装石': '선제경 고급 세트석 오픈',
 '神翼开启超级tips': '날개 활성화 초특급 힌트',
 '特级骑士圣器(随机)': '특급 기사 성구(랜덤)',
 '神仆开启超级tips': '신복 활성화 초특급 힌트',
 '宋代的代表性刑罚是？': '송대의 대표적인 징벌은?',
 '不朽基础魔卷(自选)': '불멸 기본 마법 스크롤(선택)',
 '不朽饰品魔卷(自选)': '불멸 장식품 마법 스크롤(선택)',
 '仙台境开启中级套装石': '선대경 중급 세트석 오픈',
 '探险进阶宝箱(随机)': '탐험 진화 상자(랜덤)',
 '特级骑士圣器(自选)': '특급 기사 성구(선택)',
 '阿贝拉尔多·斯福尔查': '아베라르도 스포르차',
 '关注BOSS刷新通知': 'BOSS 등장 알림',
 '机甲幻化礼包(自选)': '메카 장착 패키지(선택)',
 '兄弟你这名字可太顶了': '님 이름 쩌네요',
 '获得星魂“空间之门”': '성혼 “공간의 문” 획득',
 '修罗战神(boss)': '수라군신(보스)',
 '获得星魂“时光长河”': '성혼 “시간의 강” 획득',
 '炫彩核心礼包(自选)': '무지개 코어 패키지(선택)',
 '听星亭相遇卡(自选)': '청성정 데이트권(선택)',
 '获得星魂“魔神之躯”': '성혼 “마신의 몸” 획득',
 '怒涛摧岸神刃(主)': '세찬파도의 검(주)',
 '仙侣庆典礼包·精致': '연인 결혼식 선물·정교',
 '仙侣庆典礼包·简约': '연인 결혼식 선물·간소',
 '在极品寻宝中获得了': '보물뽑기에서 획득:',
 '时装永久·老虎头饰': '의상 영구·호랑이 모자',
 '时装永久·废土头饰': '영구 테니아·필드 의상',
 '时装永久·废土武器': '영구 무기·필드 의상',
 '鹏袭长空神枪(主)': '붕새의 기습 창(주)',
 '王不留行神镖(副)': '왕불류행 표창(보조)',
 '时装永久·废土衣服': '영구 의상·필드 의상',
 '时装永久·魔龙头饰': '영구 의상·마룡 테니아',
 '抱月长终神镖(副)': '달의 포옹 표창(보조)',
 '询问南凰泽儿的身份': '남황택아의 신분 묻기',
 '守护者boss技能': '수호자 BOSS스킬',
 '武神无畏飞镖(副)': '무신무외 표창(보조)',
 '圣诞快乐（狂战士）': '메리 크리스마스(버서커)',
 '英雄红花洞毒龙神将': '영웅 홍화동 독룡신장',
 '浪漫小小熊背饰碎片': '로맨틱 곰돌이 등 장식 조각',
 '时装永久·残疾武器': '의상 영구·숨은 즐거움 무기',
 '在神仆寻宝中获得了': '동료소환에서 획득:',
 '时装永久·冰凝武器': '영구 의상·얼음결정 무기',
 '怒浪摧岸镰刃(主)': '세찬파도의 낫(주)',
 '在装备寻宝中获得了': '장비소환에서 획득:',
 '龙战玄黄神刺(副)': '용전현황신날(보조)',
 '粽情端午（头像框）': '종정단오(프로필 프레임)',
 '驱鹏驭鲲爪刺(副)': '곤붕의 발톱(보조)',
 '粽情端午（聊天框）': '종정단오(채팅 프레임)',
 '御剑血脉怒气技伤害': '어검 혈맥궁극기 피해',
 '御剑血脉怒气技范围': '어검 혈맥궁극기 범위',
 '爱新觉罗·努尔哈赤': '아이신기오로 누루아치',
 '时装永久·残疾头饰': '의상 영구·숨은 즐거움 테니아',
 '烽火连天爪刺(副)': '봉화의 발톱(보조)',
 '切换至BOSS信息': 'BOSS정보로 변경',
 '踏岳封峦爪刺(副)': '철갑산 발톱(보조)',
 '我等乃仗剑宗精英！': '나는 장검종 정예다!',
 '时装永久·南瓜头饰': '영구 의상·호박 테니아',
 '战旗飘扬(狂战士)': '깃발 휘날리며 (버서커)',
 '前期升级才是王道！': '레벨업만이 길이다!',
 '赤日杳灵灵剑(主)': '붉은 신령 영검(주)',
 '九重极天镰刃(主)': '구중극천의 낫(주)',
 '神武开天镰刃(主)': '신무개천의 낫(주)',
 '遗失秘境意志力减少': '유실비경 의지력 감소',
 '仙侣庆典礼包·豪华': '연인 결혼식 선물·호화',
 '时装永久·圣诞头饰': '영구 의상·크리스마스 테니아',
 '时装永久·魔龙武器': '영구 의상·마룡 무기',
 '怒涛摧岸镰刃(主)': '세찬홍수의 낫(주)',
 '时装永久·军团衣服': '영구 의상·군단 의상',
 '时装永久·像素头饰': '영구 의상·아케이드 테니아',
 '刺客血脉怒气技范围': '자객 혈맥궁극기 범위',
 '劳动代表(狂战士)': '레이버 리더(버서커)',
 '特级防御光环自选箱': '최고급 방어 오라 선택 상자',
 '称兄道弟（已废弃）': '호형호제(폐기 완료)',
 '尽览昏晓仙铃(副)': '새벽여명 요령(보조)',
 '弥天星彩仙铃(副)': '천공성채 요령(보조)',
 '经乾纬坤仙铃(副)': '경건위곤 요령(보조)',
 '特级防御增益自选箱': '최고급 방어버프 선택 상자',
 '平时不怎么刷短视频': '평소에 즐겨보지 않음',
 '衡阴济阳仙铃(副)': '형음제양 요령(보조)',
 'BOSS之家重生券': '보스 요새 부활권',
 '特级防御强化自选箱': '최고급 방어 강화 선택 상자',
 '我国最大的平原是？': '중국 최대 평원은?',
 '法神无争仙铃(副)': '법신무쟁 요령(보조)',
 '赤日杳灵神铃(副)': '붉은 신령신령(보조)',
 '落日霞明神铃(副)': '낙일의 빛신령(보조)',
 '摇滚乐队（狂战士）': '록밴드(버서커)',
 '势力防守战胜利奖励': '길드방어전 승리 보상',
 '罗樱朱蔓神镜(副)': '벚나무덩굴 신경(보조)',
 '极东羽织（狂战士）': '봄의 유카타(버서커)',
 '乾坤如意棍随机神兵': '건곤여의봉 랜덤 신병',
 '夜昙未央神珠(主)': '끝없는 밤의 신주(주)',
 '罗樱朱蔓玉镜(副)': '벚나무덩굴 옥경(보조)',
 '罗樱朱蔓法珠(主)': '벚나무덩굴 마법구(주)',
 '传说背饰碎片自选箱': '유니크 장식 조각 선택 상자',
 '朝朝幕幕/朝朝暮暮': '아침저녁',
 '壮志凌云神刃(主)': '장대한 능운 신검(주)',
 '壮志凌云镰刃(主)': '장대한 능운의 낫(주)',
 '可爱布偶(狂战士)': '큐티 봉제인형(버서커)',
 '沃尔夫冈里希特霍芬': '볼프강 리히토펜(남작)',
 '赏金副本_学院试炼': '현상금던전_학원시련',
 '孤蓬万里仙铃(副)': '천고만리 요령(보조)',
 '特级状态奥义自选箱': '최고급 오의 상태 선택 상자',
 '刺客血脉怒气技伤害': '자객 혈맥궁극기 피해',
 '特级防御秘术自选箱': '최고급 방어 비술 선택 상자',
 '时装永久·军团头饰': '영구 의상·군단 테니아',
 '卡牌_帮助提示内容': '카드+도움 알림 내용',
 '装备全部部位的战甲': '전체 부위 갑옷 장착',
 '时装永久·军团武器': '영구 의상·군단 무기',
 '时装永久·残疾衣服': '의상 영구·숨은 즐거움 의상',
 '时装永久·圣殿衣服': '영구 의상·성전 의상',
 '时装永久·圣殿头饰': '영구 의상·성전 테니아',
 '时装永久·圣殿武器': '영구 의상·성전 무기',
 '新月如钩（狂战士）': '초승달(버서커)',
 '深海守护者  鱿鱼': '심해 수호자',
 '小鸡快跑·失败通知': '병아리 런·패배 통지',
 '歌坛新星（狂战士）': '라이징 스타(버서커)',
 '劳动工具(狂战士)': '작업 도구(버서커)',
 '提升随机百分比攻击': '공격 랜덤 비율 증가',
 '圣兽BOSS重生券': '성수 보스 부활권',
 '圣魔学院(狂战士)': '마법 아카데미(버서커)',
 '增加日常试炼金币量': '일상시련 금화량 증가',
 '双人 小丑炸弹碎片': '광대 강화 미사일 조각',
 '至仙遗迹·仙血主宰': '지선유적·선혈 지배자',
 '至仙遗迹-仙血主宰': '지선유적-선혈 지배자',
 '落日霞明灵剑(主)': '낙일의 빛 영검(주)',
 '互帮互助，互惠互利': '서로 서로 도와요',
 '高级神域石(龙盔)': '상급 신역의 돌(용 투구)',
 '高级神域石(龙靴)': '상급 신역의 돌(용 신발)',
 '高级神域石(龙珠)': '상급 신역의 돌(용 구슬)',
 '高级神域石(龙臂)': '상급 신역의 돌(용 완갑)',
 '高级神域石(龙篷)': '상급 신역의 돌(용 망토)',
 '高级神域石(龙肩)': '상급 신역의 돌(용 견갑)',
 '高级神域石(龙甲)': '상급 신역의 돌(용 갑옷)',
 '宠      伤：': '펫  피  해：',
 '精灵BOSS体力果': '정령 보스 체력 열매',
 '小鸡快跑·胜利通知': '병아리 런·승리 통지',
 '贪狼啸月神镖(副)': '탐랑의 달 표창(보조)',
 '激活星魂-绝世剑域': '성혼-절세검역 활성화',
 '激活星魂-星辰小人': '성혼-성신소인 활성화',
 '击败追来的厄运魔灵': '쫓아온 액운마령 처치',
 '击败妖皇回廊的敌人': '요황의 회랑 적 처치',
 '伏鹰立羽飞镖(副)': '매의 깃털 표창(보조)',
 '时装永久·甜梦武器': '영구 의상·달콤한 꿈 무기',
 '通用BOSS刷新卡': '일반 보스 갱신카드',
 '领主刷新卡（通用）': '보스 갱신카드(일반)',
 '电玩达人(狂战士)': '게임의 달인(버서커)',
 '怒涛摧岸神刺(副)': '세찬파도의 날(보조)',
 '时装永久·小丑衣服': '영구 의상·악동 의상',
 '看看祝长老有何指教': '축장로의 가르침 받기',
 'VIP投资每日领取': 'VIP투자 매일 수령',
 '电玩设备(狂战士)': '게임 디바이스(버서커)',
 '时装永久·幻兽武器': '영구 의상·신수 무기',
 '时装永久·魅影衣服': '영구 의상·용사 의상',
 '抱月长终双枪(主)': '달의 포옹 쌍창사(주)',
 '神武开天神刺(副)': '신무개천의 날(보조)',
 '英国的首都是哪里？': '영국의 수도는?',
 '今日已赠送礼物数量': '오늘 선물 완료 개수',
 '时装永久·甜梦衣服': '영구 의상·달콤한 꿈 의상',
 '圣王剑窟-圣血主宰': '성왕검굴-성혈 지배자',
 '圣王剑窟·圣血主宰': '성왕검굴·성혈 지배자',
 '都市传说(狂战士)': '어반 레전드(버서커)',
 '伏鹰立羽双枪(主)': '매의 깃털 쌍창사(주)',
 '气素霓生法珠(主)': '기소예생 마법구(주)',
 '九重极天神刺(副)': '구중극천의 날(보조)',
 '君临天下(狂战士)': '더 엠퍼러(버서커)',
 '天际归鸿法珠(主)': '천제귀홍 마법구(주)',
 '黯然销魂法珠(主)': '암영소혼 마법구(주)',
 '时装永久·甜梦头饰': '영구 의상·달콤한 꿈 테니아',
 '余晖独行双枪(主)': '석양의 빛 쌍창사(주)',
 '贪狼啸月双枪(主)': '탐랑의 달 쌍창사(주)',
 '专属BOSS挑战券': '전용 보스 도전권',
 '余晖独行飞镖(副)': '석양의 빛 표창(보조)',
 '时装永久·小丑头饰': '영구 의상·악동 테니아',
 '时装永久·甜心头饰': '영구 의상·달콤한 테니아',
 '时装永久·恶魔武器': '영구 의상·데몬 무기',
 '抱月长终飞镖(副)': '달의 포옹 표창(보조)',
 '时装永久·像素衣服': '영구 의상·아케이드 의상',
 '《昆虫记》的作者是': '《곤충기》의 저자는?',
 '战神不败爪刺(副)': '군신불패 발톱(보조)',
 '时装永久·甜心武器': '영구 의상·달콤한 무기',
 '伏鹰立羽神镖(副)': '매의 깃털 표창(보조)',
 '【天尊遗址】召唤怪': '【천존유적】소환몬스터',
 '时装永久·甜心衣服': '영구 의상·달콤한 의상',
 '时装永久·死神武器': '영구 의상·사신 무기',
 '时装永久·死神头饰': '영구 의상·사신 테니아',
 '时装永久·死神衣服': '영구 의상·사신 의상',
 '击败帝王秘境的敌人': '제왕비경의 적 처치',
 '击败辟邪山庄的敌人': '벽사산장의 적 처치',
 '九重极天爪刺(副)': '구중극천 발톱(보조)',
 '时装永久·恶魔头饰': '영구 의상·데몬 테니아',
 '时装永久·幻兽头饰': '영구 의상·신수 테니아',
 'BOSS-乱界之主': 'BOSS-난계의 주인',
 '时装永久·小丑武器': '영구 의상·악동 무기',
 'BOSS-魔化庞弘': 'BOSS-마화된 방홍',
 '时装永久·太空衣服': '영구 의상·우주 의상',
 '时装永久·太空头饰': '영구 의상·우주 테니아',
 '贵族雨伞(狂战士)': '귀족 우산(버서커)',
 '时装永久·幻兽衣服': '영구 의상·신수 의상',
 'BOSS挑战次数：': 'BOSS 도전 횟수:',
 '时装永久·恶魔衣服': '영구 의상·데몬 의상',
 '贪狼啸月飞镖(副)': '탐랑의 달 표창(보조)',
 '怒浪摧岸爪刺(副)': '세찬파도 발톱(보조)',
 '怒涛摧岸爪刺(副)': '세찬홍수 발톱(보조)',
 '龙战玄黄爪刺(副)': '용전현황 발톱(보조)',
 '时装永久·太空武器': '영구 의상·우주 무기',
 '神武开天爪刺(副)': '신무개천 발톱(보조)',
 '时装永久·帝龙武器': '영구 의상·타이론 무기',
 '校园记忆(狂战士)': '학창시절 추억 (버서커)',
 '弥天星彩神铃(副)': '천공성채신령(보조)',
 '伏鹰立羽神枪(主)': '매의 깃털 창(주)',
 '武神无畏双枪(主)': '무신무외 쌍창사(주)',
 '诛恶却邪飞镖(副)': '죄악의 표창(보조)',
 '日妖月狂双枪(主)': '일요월광 쌍창사(주)',
 '艳若惊鸿双枪(主)': '절세야경 쌍창사(주)',
 '光明神神石(唯一)': '광신 신석(유일)',
 '时装永久·蒸汽头饰': '영구 의상·증기 테니아',
 '时装永久·蒸汽衣服': '영구 의상·증기 의상',
 '时装永久·蒸汽武器': '영구 의상·증기 무기',
 '樱色浪漫（狂战士）': '벚꽃의 낭만(버서커)',
 '王不留行双枪(主)': '왕불류행 쌍창사(주)',
 '冷月花魂神镜(副)': '꽃의 넋 신경(보조)',
 '余晖独行神枪(主)': '석양의 빛 창(주)',
 '贪狼啸月神枪(主)': '탐랑의 달 창(주)',
 '罗樱朱蔓神珠(主)': '벚나무덩굴 신주(주)',
 '诛恶却邪双枪(主)': '죄악의 쌍창사(주)',
 '时装永久·圣金武器': '영구 의상·골드 무기',
 '孤蓬万里灵剑(主)': '천고만리 영검(주)',
 '查看前方强大的魔气': '강력한 마기 살펴보기',
 '黯然销魂神镜(副)': '암영소혼신경(보조)',
 '不染纤尘神珠(主)': '탈속세의 신주(주)',
 '天际归鸿神镜(副)': '천제귀홍신경(보조)',
 '日妖月狂飞镖(副)': '일요월광 표창(보조)',
 '艳若惊鸿飞镖(副)': '절세야경 표창(보조)',
 '时装永久·魔龙衣服': '영구 의상·마룡 의상',
 '圣诞核心（狂战士）': '크리스마스 코어(버서커)',
 '发财牛boss技能': '행운소 BOSS스킬',
 '冷月花魂神珠(主)': '꽃의 넋 신주(주)',
 '精灵BOSS重生券': '정령 보스 부활권',
 '本日可免费洗炼次数': '오늘 무료 제련 횟수',
 '时装永久·像素武器': '영구 의상·아케이드 무기',
 '王不留行飞镖(副)': '왕불류행 표창(보조)',
 '气素霓生神镜(副)': '기소예생신경(보조)',
 '抱月长终神枪(主)': '달의 포옹 창(주)',
 '了解最新的游戏信息': '최신 게임 정보 보기',
 '冷月花魂法珠(主)': '꽃의 넋 마법구(주)',
 '企鹅是哺乳动物吗？': '펭귄은 포유동물인가?',
 'BOSS-虚空幻灵': 'BOSS-허공환영',
 '童真之心(狂战士)': '천진난만(버서커)',
 '拿到南凰泽儿的信物': '남황택아의 신물 받기',
 '赤日杳灵神剑(主)': '붉은 신령신검(주)',
 '天际归鸿玉镜(副)': '천제귀홍 옥경(보조)',
 '不染纤尘玉镜(副)': '탈속세의 옥경(보조)',
 '落日霞明神剑(主)': '낙일의 빛신검(주)',
 '气素霓生玉镜(副)': '기소예생 옥경(보조)',
 '暗黑神神石(唯一)': '암흑신 신석(유일)',
 '黯然销魂玉镜(副)': '암영소혼 옥경(보조)',
 '孤蓬万里神铃(副)': '천고만리신령(보조)',
 '尽览昏晓神铃(副)': '새벽여명신령(보조)',
 '涅魄灭魂法珠(主)': '열백멸혼 마법구(주)',
 '浣心涤灵法珠(主)': '영혼정화 마법구(주)',
 '光逾长庚仙铃(副)': '장경성 요령(보조)',
 '冷月花魂玉镜(副)': '꽃의 넋 옥경(보조)',
 '时装永久·魅影武器': '영구 의상·용사 무기',
 '<稀薄的神王灵气>': '<희미한 신왕영기>',
 '深渊BOSS体力果': '심연 보스 체력 열매',
 '深渊BOSS重生券': '심연 보스 부활권',
 '尽览昏晓灵剑(主)': '새벽여명 영검(주)',
 '不染纤尘神镜(副)': '탈속세의 신경(보조)',
 '弥天星彩灵剑(主)': '천공성채 영검(주)',
 '烈焰兽boss技能': '화염수 BOSS스킬',
 '经乾纬坤灵剑(主)': '경건위곤 영검(주)',
 'BOSS-试炼长老': 'BOSS-시련장로',
 '衡阴济阳灵剑(主)': '형음제양 영검(주)',
 '涅魄灭魂玉镜(副)': '열백멸혼 옥경(보조)',
 '浣心涤灵玉镜(副)': '영혼정화 옥경(보조)',
 '战姬进阶石(随机)': '미호 진화석(랜덤)',
 '法神无争灵剑(主)': '법신무쟁 영검(주)',
 '时装永久·魅影头饰': '영구 의상·용사 테니아',
 '余晖独行神镖(副)': '석양의 빛 표창(보조)',
 '时空穿梭成功了么？': '시공을 초월한 건가?',
 '真龙套装石(头盔)': '진룡 세트석(투구)',
 '真龙套装石(护手)': '진룡 세트석(장갑)',
 '真龙套装石(武器)': '진룡 세트석(무기)',
 '结义或结婚专属时装': '결의 또는 결혼 전용 코스튬',
 '真龙套装石(饰品)': '진룡 세트석(장식품)',
 '解锁双属性神纹合成': '쌍속성 문양 합성 해제',
 '解锁幻翼：炽焰天翔': '환상날개:화염천우 해제',
 '真龙套装石(腰带)': '진룡 세트석(허리띠)',
 '真龙套装石(衣服)': '진룡 세트석(옷)',
 '真龙套装石(耳饰)': '진룡 세트석(귀걸이)',
 '狐狸血脉必杀技范围': '영호 혈맥 필살기 범위',
 '狐狸血脉必杀技伤害': '영호 혈맥 필살기 피해',
 '真龙套装石(项链)': '진룡 세트석(목걸이)',
 '真龙套装石(鞋子)': '진룡 세트석(신발)',
 '合金机械伏妖法器]': '합금로봇 복요법기',
 '普通黑暗石(自选)': '일반 암흑석(선택)',
 '<普通的神王灵气>': '<일반 신왕여기>',
 '黑暗神神石(唯一)': '암흑신 신석(유일)',
 '又有新鲜的肉吃了？': '또 신선한 고기가 왔군?',
 '金乌负日仙铃(副)': '금오요령(보조)',
 '妖皇回廊-妖血主宰': '요황의 회랑-요혈 지배자',
 '王不留行神枪(主)': '왕불류행창(주)',
 '邪龙套装石(法师)': '사룡 세트석(매지션)',
 '邪龙套装石(牧师)': '사룡 세트석(프리스트)',
 '妖皇回廊·妖血主宰': '요황의 회랑·요혈 지배자',
 '邪龙石礼包(随机)': '사룡석 패키지(랜덤)',
 '战兽装备宝箱(白)': '전투신수 장비상자(일반)',
 '撼地惊天镰刃(主)': '경천낫(주)',
 '天真无邪，纯洁无暇': '천진난만, 순진무구',
 '下次免费刷新时间:': '다음 무료 갱신 시간:',
 '真龙套装石(戒指)': '진룡 세트석(반지)',
 '行云流水，斩断狂澜': '동작유려, 광란차단',
 '传说天赋秘术自选箱': '유니크 특성 비술 선택 상자',
 '夜昙未央神镜(副)': '끝없는 밤의 신경(보조)',
 '鹏袭长空双枪(主)': '붕새의 기습 쌍창사(주)',
 '<浓郁的神王灵气>': '<짙은 신왕영기>',
 '接受青魅仙子的指点': '청매선자의 가르침 받기',
 '邪龙套装石(天香)': '사룡 세트석(천향)',
 '马卡里奇·康斯坦丁': '마카리치 콘스탄틴',
 '至尊属性石(随机)': '지존 속성석(랜덤)',
 '精英·王血弟子头领': '정예·국왕혈맥 제자두목',
 '精英·帝血弟子掌教': '정예·제왕혈맥 제자장교',
 '精英·皇血弟子掌教': '정예·황제혈맥 제자장교',
 '虎虎生风，活泼乱跳': '생기발랄, 원기왕성',
 '鹏袭长空飞镖(副)': '붕새의 기습 표창(보조)',
 '遭遇混沌一族的头目': '혼돈일족 두목과 만나기',
 '邪龙套装石(首饰)': '사룡 세트석(장신구)',
 '丢弃的物品超过数量': '버릴 아이템 수량 초과',
 '金乌负日神铃(副)': '금오신령(보조)',
 '天剑宗弟子，布阵！': '천검종 제자,  포진!',
 '未来科技（狂战士）': '미래 과학기술(버서커)',
 '稀有黑暗石(自选)': '희귀 암흑석(선택)',
 '稀有黑暗石(随机)': '희귀 암흑석(랜덤)',
 '光逾长庚神剑(主)': '장경성신검(주)',
 '真龙石礼包(随机)': '진룡석 패키지(랜덤)',
 '已经放入了神仆碎片': '동료 조각을 넣었습니다.',
 '真龙石礼包(自选)': '진룡석 패키지(선택)',
 '普通黑暗石(随机)': '일반 암흑석(랜덤)',
 '守护者boss普攻': '수호자 boss일반공격',
 '夜昙未央玉镜(副)': '끝없는 밤의 옥경(보조)',
 '免费邀请剩余人数：': '남은 무료 초대 인원수:',
 '烽火连天镰刃(主)': '봉화의 낫(주)',
 '龙战玄黄镰刃(主)': '용전현황낫(주)',
 '踏岳封峦镰刃(主)': '철갑산 낫(주)',
 '荣耀之光宠技自选箱': '럭셔리 펫 스킬 선택상자',
 '大型魔星矿采集次数': '대형 마성광석 채집 횟수',
 '大型星辰矿采集次数': '대형 성진광석 채집 횟수',
 '同意帮仙侣购买次数': '반려자의 횟수 구매 수락',
 '烈焰兽boss普攻': '화염수 boss일반공격',
 '了解最新的游戏情报': '최신 게임 정보 알아보기',
 '轩辕伏羲琴随机神兵': '헌원복희금 랜덤 신병',
 '战兽装备宝箱(橙)': '전투신수 장비상자(전설)',
 '马提亚斯 哈比希茨': '마티아스 하비히츠',
 '乖巧可人，单纯好奇': '호감형, 단순한 호기심쟁이',
 '首充后#r免费领取': '첫 충전 후#r무료 수령',
 '幽冥BOSS体力果': '저승 보스 체력 열매',
 '幽冥BOSS重生券': '저승 보스 부활권',
 '战兽装备宝箱(金)': '전투신수 장비상자(초월)',
 '生      命:': 'H      P:',
 'NB·PLUS礼包': 'NB·PLUS 패키지',
 '鹏袭长空神镖(副)': '붕새의 기습 표창(보조)',
 '校尉首饰武器任选包': '교위장신구무기 선택 선물',
 '玄冰降魔剑随机神兵': '현빙강마검 랜덤 신병',
 '生      命：': 'H      P：',
 '忠心护主，众灵守护': '충심수호, 정령비호',
 '战兽装备宝箱(红)': '전투신수 장비상자(신화)',
 '聪明伶俐，铁齿铜牙': '똘똘함, 달변가',
 '驱鹏驭鲲镰刃(主)': '곤붕의 낫(주)',
 '等      级：': '레      벨：',
 '生命加成\\攻击加成': 'HP 보너스/공격 보너스',

In [4]:
text = "[color=#F7C358][size=40]离线挂机特权[/color][/size]	[color=#F7C358][size=40]오프라인 자동전투 패스[/color][/size]	j界面文本.xlsx"
suffix_tags = list(set(re.findall("\[\/.*?\]", text)))  # e.g. ['[/color]', '[/size]']
suffix_tags

['[/size]', '[/color]']

In [5]:
suffix_tag_types = list(set(re.findall("\[\/(.*?)\]", text)))  # e.g.['size', 'color']
suffix_tag_types

['color', 'size']

In [6]:
regex = "|".join([r"\[{0}=.*?\]".format(tag_type) for tag_type in suffix_tag_types])  # e.g.'\[size=.*?\]|\[color=.*?\]'
regex

'\\[color=.*?\\]|\\[size=.*?\\]'

In [7]:
prefix_tags = list(set(re.findall(regex, text)))  # e.g. ['[color=#F7C358]', '[size=40]']
prefix_tags

['[color=#F7C358]', '[size=40]']

In [8]:
tags_all = suffix_tags + prefix_tags  # e.g. ['[/color]', '[/size]', '[color=#F7C358]', '[size=40]']
tags_all

['[/size]', '[/color]', '[color=#F7C358]', '[size=40]']

In [9]:
from tqdm.notebook import tqdm

for index, row in tqdm(df.iterrows(), total=df.shape[0]):
    for column in df.columns:
        if row[column] is not None:
            text = str(row[column])
            # HTML标签预处理
            suffix_tags = list(
                set(re.findall("|".join(["\[\/.*?\]", "\<\/.*?\>"]), text)))  # e.g. ['[/color]', '[/size]']
            suffix_tag_types = [re.search("\w+", tag).group() for tag in suffix_tags]  # e.g.['size', 'color']
            regex = "|".join(
                [r"\[{0}=.*?\]".format(tag_type) for tag_type in suffix_tag_types] +
                [r"\<{0}=.*?\>".format(tag_type) for tag_type in suffix_tag_types])  # e.g.'\[size=.*?\]|\[color=.*?\]'
            prefix_tags = list(set(re.findall(regex, text) if regex else []))  # e.g. ['[color=#F7C358]', '[size=40]']
            tags_all = suffix_tags + prefix_tags  # e.g. ['[/color]', '[/size]', '[color=#F7C358]', '[size=40]']
            for tag in tags_all:
                text = text.replace(tag, "<code>{0}</code>".format(tag))

            # 术语预处理
            for glossary_source, glossary_target in glossary_dict.items():
                text = text.replace(glossary_source,
                                    "<start>{0}<middle>{1}<end>".format(glossary_source, glossary_target))
            df.at[index, column] = text
df

  0%|          | 0/581 [00:00<?, ?it/s]

,简体1,简体2,简体3
0,<start>狩猎<middle>사냥<end>商<start>人<middle>사람<end>,None,None
1,图鉴,None,None
2,再次点击使用加速药<start>水<middle>수<end>,None,None
3,点击任务的传送按钮,None,None
4,点击<start>确认<middle>확인<end>传送,None,None
...,...,...,...
576,第6日完成所有任务,None,None
577,第7日完成所有任务,None,None
578,<start>狩猎<middle>사냥<end>商<start>人<middle>사람<en...,<start>狩猎<middle>사냥<end>商<start>人<middle>사람<en...,None
579,<start>狩猎<middle>사냥<end>商<start>人<middle>사람<en...,<start>狩猎<middle>사냥<end>商<start>人<middle>사람<en...,None
580,<start>狩猎<middle>사냥<end>商<start>人<middle>사람<en...,<start>狩猎<middle>사냥<end>商<start>人<middle>사람<en...,None

In [10]:
df.to_excel("實時同步翻譯文本_tagged.xlsx", index=False)